import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link"
import "./globals.css";
import { FaBars, FaTimes, FaBehance, FaInstagram } from 'react-icons/fa';
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="fixed w-full top-0 z-10 flex items-center justify-between p-6 text-white bg-black/20">
            <Link href="/"><div className="text-lg font-bold">HBa</div></Link>
            <div className="lg:hidden">
              <Sheet>
                <SheetTrigger asChild>
                  <button className="text-white">
                    <FaBars className="w-6 h-6" />
                  </button>
                </SheetTrigger>
                <SheetContent className="bg-black text-white p-4 py-8">   
                <nav className="flex flex-col items-center space-y-8 pt-10">
                   <Link href="/" className="hover:underline text-xl">
                      Home
                    </Link>
                    <Link href="/portfolio" className="hover:underline text-xl">
                      Portfolio
                    </Link>
                    <Link href="/about" className="hover:underline text-xl">
                      About
                    </Link>
                    <Link href="/contact" className="hover:underline text-xl">
                      Contact
                    </Link>
                    <div className="flex space-x-4 mt-4">
                      <Link href="#" className="hover:underline">
                        <FaBehance className="w-8 h-8" />
                      </Link>
                      <Link href="#" className="hover:underline">
                        <FaInstagram className="w-8 h-8" />
                      </Link>
                    </div>
                  </nav>
                </SheetContent>
              </Sheet>
            </div>
            <nav className="hidden lg:flex space-x-8">
              <Link href="/portfolio" className="hover:underline">
                Portfolio
              </Link>
              <a href="#" className="hover:underline">
                About
              </a>
              <a href="#" className="hover:underline">
                Contact
              </a>
            </nav>
            <div className="hidden lg:flex space-x-4">
              <a href="#" className="hover:underline">
                <FaBehance className="w-6 h-6" />
              </a>
              <a href="#" className="hover:underline">
                <FaInstagram className="w-6 h-6" />
              </a>
            </div>
          </div>
        <div className="h-full ">
           {children}
        </div>
        
<footer className="py-4 bg-black text-white">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center">
            <div className="bg-gray-500/25 h-10 w-10 rounded-full me-3 bg-background"></div>
            <span className="text-lg font-semibold">Giraffe with a Camera</span>
          </div>
          <div>&copy; {new Date().getFullYear()}</div>
        </div>
      </footer>

      </body>
    </html>
  );
}
